Data_Preparation:
  test_size: 0.25
  random_state: 42


Train:
  Random_Forest:
    n_estimators: 479
    criterion: 'squared_error'
    max_depth: 17
    max_features: 1
    min_samples_split: 9
    min_samples_leaf: 2
    max_samples: 0.6603673526197066
    verbose: 1
    n_jobs: -1
  
  LightGBM:
    n_estimators: 154
    max_depth: 27
    learning_rate: 0.22234435854395157
    subsample: 0.7592213724048168
    min_child_weight: 20
    min_split_gain: 0.004604680609280751
    reg_lambda: 97.81002379097947
    n_jobs: -1